server:
  port: ${SERVER_PORT:8082}

logging:
  file:
    name: logs/proxy.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    com.unilink: DEBUG

proxy:
  websocket:
    port: ${PROXY_WEBSOCKET_PORT:8889}
    access-path: ${PROXY_WEBSOCKET_ACCESS_PATH:/unilink/access}
    worker-path: ${PROXY_WEBSOCKET_WORKER_PATH:/unilink/worker}
    heartbeat-interval: ${PROXY_WEBSOCKET_HEARTBEAT_INTERVAL:30}
    heartbeat-timeout: ${PROXY_WEBSOCKET_HEARTBEAT_TIMEOUT:60}
